// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetApis():Promise<api.Apis>;

export function Joke(arg1:string):Promise<string>;
