// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApis() {
  return window['go']['main']['App']['GetApis']();
}

export function Joke(arg1) {
  return window['go']['main']['App']['Joke'](arg1);
}
