on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.18, 1.19, 1.20 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: build release
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Install package
        run: |
          sudo apt update -y && sudo apt-get -y install libwebkit2gtk-4.0-dev

      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - run: wails build -upx -upxflags="--best --lzma" -ldflags="-X 'main.Version=${{ github.ref_name }}'" -platform linux/amd64 -o joke-pop-linux-amd64

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/joke-pop-linux-amd64
          asset_name: joke-pop-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
          body: Release ${{ github.ref }}